# 안녕하세요^^ 
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

# 안녕하세요^^ 
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

# (실습준비) 데이터 불러오기부터

* 17년도부터 21년도 까지의 데이터를 train set, 22년도의 6개월치 데이터를 test set 으로 설정합니다.

In [59]:
#from google.colab import drive
#drive.mount('/content/drive')

In [60]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 학습 데이터 로딩
df_total = pd.read_csv('df_total.csv')

---

# 1. 데이터 전처리

#### [실습문제1] 열 추가 
* 기존 '기준일ID'열에서 날짜 데이터를 추출하여 새로운 열로 추가 합니다.
    - pd.to_datetime() 함수를 사용해 '기준일ID'열을 datetime 형식으로 변경하겠습니다.
    - year, month, day 열로 기존 데이터 프레임에 연월일 정보를 저장합니다.
    - 데이터 프레임 열에 대해 날짜 정보를 얻을 때에는 **dt.year**, **dt.month**, **dt.day** 속성을 사용합니다.

In [61]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

df_total['기준일ID'] = pd.to_datetime(df_total['기준일ID'])

df_total['year'] = df_total['기준일ID'].dt.year
df_total['month'] = df_total['기준일ID'].dt.month
df_total['day'] = df_total['기준일ID'].dt.day

df_total

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,year,month,day
0,2017-01-01,0,43922.2281,953.7652,627.7225,927.6134,2025.0630,2278.7336,1744.8161,1713.6754,...,1754.6515,1636.4175,1521.3668,1728.0639,1484.4518,1238.2606,3670.0451,2017,1,1
1,2017-01-01,1,43763.4929,962.2909,633.3292,970.6215,2045.7002,2412.6287,1765.7725,1765.1171,...,1700.9196,1619.3672,1474.8418,1661.3750,1470.3009,1098.4788,3568.8258,2017,1,1
2,2017-01-01,2,43561.5708,932.2939,613.6027,964.3505,2057.3601,2419.0941,1734.0569,1746.3940,...,1660.6697,1660.9852,1511.4103,1635.0352,1441.0173,1112.3632,3541.2620,2017,1,1
3,2017-01-01,3,43928.9929,926.3617,609.7009,983.2400,2100.5071,2480.1898,1780.3833,1723.6640,...,1678.9374,1626.8350,1516.5837,1665.8781,1471.2127,1098.3154,3630.0822,2017,1,1
4,2017-01-01,4,44150.2973,922.8893,607.4184,990.0534,2128.2729,2531.6549,1774.7853,1752.0073,...,1678.6174,1640.9056,1513.5035,1653.2704,1435.5180,1090.4059,3569.1653,2017,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43507,2021-12-31,19,33304.5400,569.3452,374.9229,702.9942,1195.0912,1818.2627,1434.7351,1439.8129,...,1136.8778,1399.4513,1262.9415,1342.7762,1058.0542,749.3935,2239.1210,2021,12,31
43508,2021-12-31,20,33368.7201,599.9827,395.0698,806.5718,1232.5401,1781.4567,1441.6411,1469.7313,...,1124.4243,1414.3330,1224.8609,1336.5298,1056.6818,756.4905,2226.3545,2021,12,31
43509,2021-12-31,21,34083.1721,630.5049,415.1424,825.4794,1360.3197,1866.0852,1428.3237,1490.6164,...,1174.9639,1477.2012,1250.2445,1336.1856,1042.3110,750.1392,2249.0323,2021,12,31
43510,2021-12-31,22,34380.0806,618.6265,407.3311,831.6651,1364.7723,1899.4216,1416.2191,1473.4710,...,1171.6865,1488.2721,1269.3231,1334.5079,1045.8411,762.5466,2263.6665,2021,12,31
43511,2021-12-31,23,37074.2785,734.2128,483.3418,895.2420,1594.0355,2116.7695,1519.3632,1552.7195,...,1251.8968,1514.6940,1379.1155,1319.0559,1138.3249,816.1801,2520.7282,2021,12,31

#### [실습문제2] 불필요한 열 제거 및 열 이름 변경
* df_total과 df_test에서 '총생활인구수'외에 불필요한 열을 제거 하도록 하겠습니다.
* 시간 데이터를 남기고, '시간대구분' column 을 'hour'로 rename 하도록 하겠습니다.

In [62]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

df_total = df_total[['year','month','day','시간대구분','총생활인구수']]
df_total.rename(columns={'시간대구분':'hour'},inplace=True)

C:\Users\PC\AppData\Local\Temp\ipykernel_17024\615169809.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total.rename(columns={'시간대구분':'hour'},inplace=True)

#### [실습문제3] 시프트 & 롤링
* shift()를 활용하여 이동할 행 수를 지정합니다.
* rolling()을 활용하여 추가할 이동평균 수를 지정합니다.

In [63]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

df_total['1d'] = df_total['총생활인구수'].shift(24)
df_total['7d'] = df_total['총생활인구수'].shift(24*7)
df_total["14d"] = df_total['총생활인구수'].shift(24*14)
df_total["28d"] = df_total['총생활인구수'].shift(24*28)
df_total["29d"] = df_total['총생활인구수'].shift(24*28*2)


df_total["30d"] = df_total['총생활인구수'].shift(24*28*4)
df_total["31d"] = df_total['총생활인구수'].shift(24*28*6)
df_total["32d"] = df_total['총생활인구수'].shift(24*28*8)
df_total["33d"] = df_total['총생활인구수'].shift(24*28*10)
df_total["34d"] = df_total['총생활인구수'].shift(24*28*12)

df_total["35d"] = df_total['총생활인구수'].shift(24*28*5)

df_total["36d"] = df_total['총생활인구수'].shift(24*28*7)

df_total["37d"] = df_total['총생활인구수'].shift(24*28*9)

df_total["38d"] = df_total['총생활인구수'].shift(24*28*11)

C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total['1d'] = df_total['총생활인구수'].shift(24)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total['7d'] = df_total['총생활인구수'].shift(24*7)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["14d"] = df_total['총생활인구수'].shift(24*14)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["28d"] = df_total['총생활인구수'].shift(24*28)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["29d"] = df_total['총생활인구수'].shift(24*28*2)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["30d"] = df_total['총생활인구수'].shift(24*28*4)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["31d"] = df_total['총생활인구수'].shift(24*28*6)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["32d"] = df_total['총생활인구수'].shift(24*28*8)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["33d"] = df_total['총생활인구수'].shift(24*28*10)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["34d"] = df_total['총생활인구수'].shift(24*28*12)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["35d"] = df_total['총생활인구수'].shift(24*28*5)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["36d"] = df_total['총생활인구수'].shift(24*28*7)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["37d"] = df_total['총생활인구수'].shift(24*28*9)
C:\Users\PC\AppData\Local\Temp\ipykernel_17024\2220727192.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total["38d"] = df_total['총생활인구수'].shift(24*28*11)

In [64]:
#abc=[2017,2018,2019,2020,2021]

#for i in abc:
    #globals()['a_'+str(i)]=df_total[(df_total['year']==i)]
    #globals()['a_'+str(i)]=globals()['a_'+str(i)]['총생활인구수']

#a_2017

In [65]:

#pd.set_option('display.max_row', 500)

#abc=df_total[(df_total['year']==2019)&(df_total['month']==10)]

#abc

In [66]:
#f, axes = plt.subplots(5, 1)
#f.set_size_inches((30, 15))
#plt.subplots_adjust(wspace = 0.3, hspace = 0.3)

# [0, 1] 위치 막대 그래프
#axes[0].plot(a_2017)

# [1, 3] 위치 선 그래프
#axes[1].plot(a_2018)

#axes[2].plot(a_2019)
#axes[3].plot(a_2020)
#axes[4].plot(a_2021)


#plt.show()

#### [실습문제4] 결측치 처리 및 불필요한 열 제거
* 롤링 & 시프트 과정에서 발생한 결측치를 처리하도록 하겠습니다.
* 불필요한 열을 추가로 제거 하겠습니다.(시간 관련 행들)

In [67]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

df_total = df_total.drop(['year','month','day','hour'], axis=1)
df_total = df_total.dropna()

#### [실습문제5] train, test 데이터 나누기
* df_total과 df_test를 각각 train_x, train_y, test_x, test_y 로 나누어 주세요.
* 인덱스를 리셋 해주세요.

In [68]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

train_x = df_total.iloc[ :,1:]
train_y = df_total.iloc[ :,:1]



train_x

,1d,7d,14d,28d,29d,30d,31d,32d,33d,34d,35d,36d,37d,38d
8064,45112.4820,44677.1617,44847.5962,44384.9380,40145.0531,42675.1030,43126.9537,41688.5709,42059.8066,43922.2281,41718.4941,44376.8584,42571.3973,39936.7089
8065,45715.2801,44873.1739,44919.6376,44548.6796,40332.1435,43064.2236,43424.5640,41826.3140,42189.9046,43763.4929,41873.2445,44445.7738,42615.5937,39713.8903
8066,46067.3717,45010.8496,44944.5506,44720.0865,40521.2266,43267.3973,43403.4560,41901.0204,42157.0515,43561.5708,41903.4261,44685.6477,42752.3340,39838.4925
8067,46099.9158,45332.3716,45332.6168,45093.9557,40682.5043,44011.8941,43756.1943,42118.1170,42757.1032,43928.9929,42066.3503,45222.5596,42863.2955,40121.4797
8068,46353.8109,45520.0498,45353.5027,45114.9562,40638.0975,44073.2148,43923.2058,42163.1318,42843.0506,44150.2973,42178.5760,45406.4385,42999.2933,40388.8146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43507,34687.7515,35837.1203,36775.0743,36013.9567,34931.0708,36479.1513,35725.8387,36206.5575,36308.4301,36124.6559,36092.9204,35325.3347,36005.7428,36661.0530
43508,34728.1718,35867.0404,36826.4918,35383.6835,34521.9157,36984.5073,35937.5236,35983.9653,36042.4565,37110.6276,36272.8813,35742.5170,36029.8125,36800.4719
43509,35767.8222,36299.9836,36432.6342,35644.0511,34783.8555,37377.4359,36496.1660,36089.1846,36884.5882,37729.4349,36919.9274,35872.9378,36799.8468,37111.8435
43510,36193.0573,36409.8234,36788.8725,36039.1858,34728.1786,37664.3727,36760.2300,37392.3883,38173.2479,37874.7481,37458.0578,36492.2195,37579.2923,38134.3374
43511,38468.1344,39266.3421,39538.7175,39057.8215,37927.4154,40251.1247,39368.6175,40449.8401,40667.0770,40849.6406,40030.1183,39285.1988,40337.2272,40884.1169

In [69]:
train_x

,1d,7d,14d,28d,29d,30d,31d,32d,33d,34d,35d,36d,37d,38d
8064,45112.4820,44677.1617,44847.5962,44384.9380,40145.0531,42675.1030,43126.9537,41688.5709,42059.8066,43922.2281,41718.4941,44376.8584,42571.3973,39936.7089
8065,45715.2801,44873.1739,44919.6376,44548.6796,40332.1435,43064.2236,43424.5640,41826.3140,42189.9046,43763.4929,41873.2445,44445.7738,42615.5937,39713.8903
8066,46067.3717,45010.8496,44944.5506,44720.0865,40521.2266,43267.3973,43403.4560,41901.0204,42157.0515,43561.5708,41903.4261,44685.6477,42752.3340,39838.4925
8067,46099.9158,45332.3716,45332.6168,45093.9557,40682.5043,44011.8941,43756.1943,42118.1170,42757.1032,43928.9929,42066.3503,45222.5596,42863.2955,40121.4797
8068,46353.8109,45520.0498,45353.5027,45114.9562,40638.0975,44073.2148,43923.2058,42163.1318,42843.0506,44150.2973,42178.5760,45406.4385,42999.2933,40388.8146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43507,34687.7515,35837.1203,36775.0743,36013.9567,34931.0708,36479.1513,35725.8387,36206.5575,36308.4301,36124.6559,36092.9204,35325.3347,36005.7428,36661.0530
43508,34728.1718,35867.0404,36826.4918,35383.6835,34521.9157,36984.5073,35937.5236,35983.9653,36042.4565,37110.6276,36272.8813,35742.5170,36029.8125,36800.4719
43509,35767.8222,36299.9836,36432.6342,35644.0511,34783.8555,37377.4359,36496.1660,36089.1846,36884.5882,37729.4349,36919.9274,35872.9378,36799.8468,37111.8435
43510,36193.0573,36409.8234,36788.8725,36039.1858,34728.1786,37664.3727,36760.2300,37392.3883,38173.2479,37874.7481,37458.0578,36492.2195,37579.2923,38134.3374
43511,38468.1344,39266.3421,39538.7175,39057.8215,37927.4154,40251.1247,39368.6175,40449.8401,40667.0770,40849.6406,40030.1183,39285.1988,40337.2272,40884.1169

---

## 다음 단계를 위해서 데이터를 저장하겠습니다.

In [70]:
# CSV로 저장
train_x.to_csv('train_x.csv', index = False)
train_y.to_csv('train_y.csv', index = False)

---